import type {Metadata} from "next";
import "./globals.css";
import {Header} from "@/src/app/header";
import {Roboto_Flex, Roboto_Mono} from 'next/font/google';
import clsx from "clsx";
import {Navbar} from "@/src/app/navbar";


const robotoFlex = Roboto_Flex({
    subsets: ['latin'],
    axes: ['GRAD', 'XTRA', 'opsz', 'wdth'],
    display: 'swap',
    variable: '--roboto-flex',
});

const robotoMono = Roboto_Mono({
    subsets: ['latin'],
    variable: '--roboto-mono',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={clsx('body', robotoFlex.variable, robotoMono.variable)}
        >
        <Header/>
        <Navbar/>
        {children}
        </body>
        </html>
    );
}
